# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "TBUS 2017"
email: "admin@tbus.ca"
description: "Team Building Under the Stars 2017"
baseurl: ""
url: "https://tbus.ca"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "tbus.ca"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"


# Organizer Info
organizerName: "TBUS"
organizerAlternateName: "We are TBUS"
organizerDescription: "TBUS pushes industry experts to new heights."
organizerEmail: "admin@tbus.ca"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://tbus.ca"

# Head
metaKeywords: "event, tbus, 2017, leaders, development, conference, toronto, retreat"
twitterAccount: "@TBUS"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfgA2Wr1IpzKsqiyT90VLxJLOOvud_qeLEvEQlObUM6RDg4Kg/viewform"
c4sponsorsUrl: "/assets/TBUS_Conf_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSfgA2Wr1IpzKsqiyT90VLxJLOOvud_qeLEvEQlObUM6RDg4Kg/viewform", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSfgA2Wr1IpzKsqiyT90VLxJLOOvud_qeLEvEQlObUM6RDg4Kg/viewform", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "TBUS is <typeout>"
eventDate: "July  7th - 10th, 2017"
typeoutTextValues: '"", "Now", "Curious", "Forging the Path", "Under the Stars", "Leading Industries"'
typeoutFallback: "Under the Stars"
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSfgA2Wr1IpzKsqiyT90VLxJLOOvud_qeLEvEQlObUM6RDg4Kg/viewform", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About TBUS"
aboutBlock:
 - {title: "Retreat", image: "conference.jpg", text: " For 2017, we will be bringing industry leaders to an unbelievable setting north of Toronto to share their stories under the stars." }
 - {title: "Conference", image: "workshop.jpg", text: "3 tracks of world class talks. From build software to building bridges, this will be a weekend you never forget." }
 - {title: "Hackathon", image: "hackathon.jpg", text: "An unprecedented 48hr sprint to build a hot tub from nothing. Team building like you have never seen before." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from around the country"}
 - {count: "96", specialCharacter: "+", info: "hours", detail: "of round the clock events"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "focus on leadership, new skills, or even canoes!"}
 - {count: "100", specialCharacter: "+", info: "years", detail: "of combined industry experience"}


# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "West Sugar Island"
eventLocationLink: ""
eventStreetAddress: "Rice Lake"
eventAddressLocality: "Roseneath"
eventAddressLocalityRegion: "Ontario"
eventPostalCode: "K0K2X0"
eventAddressCountry: "Canada"
eventStartTime: "2017-07-06T09:00"
eventDoorTime: "09:00"
eventEndTime: "2017-07-09T19:00"

eventPlaceCoordinates: "44.1318546,-78.2469026"
mapCenterCoordinates: "44.1318546,-78.2469026"
mapMobileCenterCoordinates: "44.1318546,-78.2469026"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "island_0.JPG"
venueSmallImage1: "island_1.JPG"
venueSmallImage2: "island_2.JPG"
venueSmallImage3: "island_3.JPG"
venueTitle: "West Sugar Island"
venueFeatures: ["2 Chalets", "Open air workshops", "Unparalleled environment"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "TBUS2017"
twitterFeed: "http://lviv.TBUS.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://TBUS.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open until July 1st. Tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all events. Accommodation is included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "399"
  priceCurrency: "CAD"
  ticketsNumber: "10"
  ribbon: "-20%"
  buyButtonLink: "https://www.eventbrite.ca/e/tbus-conf-2017-tickets-34933673558"
  buyButtonText: "Buy Now"
  ticketContentList: ["Limited Availability", "4 Days, 3 Nights", "Lodging Included"]
  validFrom: "2017-05-01T10:00"
  validThrough: "2017-05-30T23:59"
  soldOut: true
  soldOutText: "Sold Out"
 -
  name: "Regular"
  price: "499"
  priceCurrency: "CAD"
  ticketsNumber: "20"
  featured: true
  buyButtonLink: "https://www.eventbrite.ca/e/tbus-conf-2017-tickets-34933673558"
  buyButtonText: "Buy Now"
  ticketContentList: ["Buy Now!", "4 Days, 3 Nights", "Lodging Included"]
  validFrom: "2017-06-01T00:00"
  validThrough: "2017-07-05T23:59"
  disabled: false
 -
  name: "Dog"
  price: "99"
  priceCurrency: "CAD"
  ticketsNumber: "10"
  ribbon: "-80%"  
  buyButtonLink: "https://www.eventbrite.ca/e/tbus-conf-2017-tickets-34933673558"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a human be present with you at check in. Failure to be a dog will result in your ticket being cancelled without refund"
  ticketContentList: ["Bring your dog", "Dedicated event track. We are serious!", "4sq KM to Explore."]
  validFrom: "2017-05-01T10:00"
  validThrough: "2017-07-05T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=TBUSLviv", icon: "twitter"}
 - {link: "https://facebook.com/TBUSLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://TBUS.ca", text: "TBUS.ca"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:admin@TBUS.ca", text: "admin@TBUS.ca"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "TBUS 2017"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "TBUS strives to provide socially cocncious events which bring together a diverse set of speakers on topics far and wide."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "44.1318546,-78.2469026"
logisticsMapMobileCenterCoordinates: "44.1318546,-78.2469026"
logisticsMapAutoDirections: true

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around West Sugar island"
directionDetailsCards:
 - {title: "From the Mainland", information: 'A charter boat will be running bi-daily for attendees and speakers.'}
 - {title: "Public Transit", information: 'TBUS Conf is not accessible via public transit :( '}
 - {title: "Lodging", information: 'TBUS Conf provides both chalet & outdoor accomodations for attendees.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Accomodation"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Central Cabin"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Boat House"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Clearing (camping)"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Details"}
   -
    title: "Surrounding Area"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Details"}

# Hackathon
hackathonTitle: "Build a Tub"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Build a Tub"
hackathonRows:
 - {title: "Tub Design", image: "hackathon-0.png", details: "Think you know how to build a tub? put your skills to the test."}
 - {title: "In Tub Seating", image: "hackathon-1.jpg", details: "A tub is nothing if it does not have great seating. Optomize the space and make this a tub to remember."}
 - {title: "Heating", image: "hackathon-2.png", details: "No one wants to be in a cold tub. Without your hack, we will be sitting in a lake, beside a lake. No one wants that."}
 - {title: "Circulation", image: "hackathon-3.png", details: "A tub without circulation is like a body without a heart - dead. Make the water flow."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-1.png", info: "Towel Service"}
 - {title: "1st Place", image: "prize-3.png", info: "Invite only Tub party (no touching)"}
 - {title: "3rd Place", image: "prize-2.png", info: "Personal Tub Ducky"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "West Sugar Island"
hackathonLocationLink: ""
hackathonStreetAddress: "West Sugar Island"
hackathonAddressLocality: "Roseneath"
hackathonAddressLocalityRegion: "Ontario"
hackathonPostalCode: "K0K2X0"
hackathonAddressCountry: "Canada"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2017-08-06T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2017-08-10T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "44.1318546,-78.2469026"
hackathonMapCenterCoordinates: "44.1318546,-78.2469026"
hackathonMapMobileCenterCoordinates: "44.1318546,-78.2469026"
